// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAmpType() {
  return window['go']['main']['App']['GetAmpType']();
}

export function GetCurrentDevice() {
  return window['go']['main']['App']['GetCurrentDevice']();
}

export function GetPedalType() {
  return window['go']['main']['App']['GetPedalType']();
}

export function GetPod() {
  return window['go']['main']['App']['GetPod']();
}

export function IsStarted() {
  return window['go']['main']['App']['IsStarted']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function QueryAllPresets(arg1) {
  return window['go']['main']['App']['QueryAllPresets'](arg1);
}

export function QueryAllSets(arg1) {
  return window['go']['main']['App']['QueryAllSets'](arg1);
}

export function QueryCurrentPreset(arg1) {
  return window['go']['main']['App']['QueryCurrentPreset'](arg1);
}

export function QueryCurrentPresetID(arg1) {
  return window['go']['main']['App']['QueryCurrentPresetID'](arg1);
}

export function QueryCurrentSetID(arg1) {
  return window['go']['main']['App']['QueryCurrentSetID'](arg1);
}

export function QueryPreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryPreset'](arg1, arg2, arg3);
}

export function ReloadPreset() {
  return window['go']['main']['App']['ReloadPreset']();
}

export function SavePreset() {
  return window['go']['main']['App']['SavePreset']();
}

export function SetAmpActive(arg1, arg2) {
  return window['go']['main']['App']['SetAmpActive'](arg1, arg2);
}

export function SetAmpParameterValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAmpParameterValue'](arg1, arg2, arg3);
}

export function SetAmpType(arg1, arg2) {
  return window['go']['main']['App']['SetAmpType'](arg1, arg2);
}

export function SetCabParameterValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCabParameterValue'](arg1, arg2, arg3);
}

export function SetCabType(arg1, arg2) {
  return window['go']['main']['App']['SetCabType'](arg1, arg2);
}

export function SetCurrentPresetName(arg1) {
  return window['go']['main']['App']['SetCurrentPresetName'](arg1);
}

export function SetDTClass(arg1, arg2) {
  return window['go']['main']['App']['SetDTClass'](arg1, arg2);
}

export function SetDTClass2(arg1, arg2) {
  return window['go']['main']['App']['SetDTClass2'](arg1, arg2);
}

export function SetDTMode(arg1, arg2) {
  return window['go']['main']['App']['SetDTMode'](arg1, arg2);
}

export function SetDTMode2(arg1, arg2) {
  return window['go']['main']['App']['SetDTMode2'](arg1, arg2);
}

export function SetDTTopology(arg1, arg2) {
  return window['go']['main']['App']['SetDTTopology'](arg1, arg2);
}

export function SetDTTopology2(arg1, arg2) {
  return window['go']['main']['App']['SetDTTopology2'](arg1, arg2);
}

export function SetNotify(arg1) {
  return window['go']['main']['App']['SetNotify'](arg1);
}

export function SetPedalActive(arg1, arg2) {
  return window['go']['main']['App']['SetPedalActive'](arg1, arg2);
}

export function SetPedalBoardItemActive(arg1, arg2) {
  return window['go']['main']['App']['SetPedalBoardItemActive'](arg1, arg2);
}

export function SetPedalBoardItemParameterValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalBoardItemParameterValue'](arg1, arg2, arg3);
}

export function SetPedalBoardItemParameterValueMax(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalBoardItemParameterValueMax'](arg1, arg2, arg3);
}

export function SetPedalBoardItemParameterValueMin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalBoardItemParameterValueMin'](arg1, arg2, arg3);
}

export function SetPedalBoardItemPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalBoardItemPosition'](arg1, arg2, arg3);
}

export function SetPedalBoardItemType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalBoardItemType'](arg1, arg2, arg3);
}

export function SetPedalBoardParameterValue(arg1, arg2) {
  return window['go']['main']['App']['SetPedalBoardParameterValue'](arg1, arg2);
}

export function SetPedalParameterValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalParameterValue'](arg1, arg2, arg3);
}

export function SetPedalType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPedalType'](arg1, arg2, arg3);
}

export function SetPreset(arg1, arg2) {
  return window['go']['main']['App']['SetPreset'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
